// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rijuCB/RAFT2/node (interfaces: Inode)

// Package mock_node is a generated GoMock package.
package mock_node

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInode is a mock of Inode interface.
type MockInode struct {
	ctrl     *gomock.Controller
	recorder *MockInodeMockRecorder
}

// MockInodeMockRecorder is the mock recorder for MockInode.
type MockInodeMockRecorder struct {
	mock *MockInode
}

// NewMockInode creates a new mock instance.
func NewMockInode(ctrl *gomock.Controller) *MockInode {
	mock := &MockInode{ctrl: ctrl}
	mock.recorder = &MockInodeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInode) EXPECT() *MockInodeMockRecorder {
	return m.recorder
}

// CandidateAction mocks base method.
func (m *MockInode) CandidateAction() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CandidateAction")
}

// CandidateAction indicates an expected call of CandidateAction.
func (mr *MockInodeMockRecorder) CandidateAction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CandidateAction", reflect.TypeOf((*MockInode)(nil).CandidateAction))
}

// FollowerAction mocks base method.
func (m *MockInode) FollowerAction() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FollowerAction")
}

// FollowerAction indicates an expected call of FollowerAction.
func (mr *MockInodeMockRecorder) FollowerAction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowerAction", reflect.TypeOf((*MockInode)(nil).FollowerAction))
}

// LeaderAction mocks base method.
func (m *MockInode) LeaderAction() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LeaderAction")
}

// LeaderAction indicates an expected call of LeaderAction.
func (mr *MockInodeMockRecorder) LeaderAction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaderAction", reflect.TypeOf((*MockInode)(nil).LeaderAction))
}

// PerformRankAction mocks base method.
func (m *MockInode) PerformRankAction() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PerformRankAction")
}

// PerformRankAction indicates an expected call of PerformRankAction.
func (mr *MockInodeMockRecorder) PerformRankAction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformRankAction", reflect.TypeOf((*MockInode)(nil).PerformRankAction))
}
